"""Initial migration after reset

Revision ID: 117163410482
Revises: 
Create Date: 2024-05-04 02:37:43.707920

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '117163410482'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        # Temporarily allow NULL
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('court_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('reserved_seat', sa.Integer(), nullable=True))
    
    # Populate the new columns with default or derived values
    op.execute(
        '''
        UPDATE reservation
        SET user_name = (SELECT username FROM user WHERE user.id = reservation.user_id),
            court_name = (SELECT name FROM court WHERE court.id = reservation.court_id),
            reserved_seat = 1  # Assuming a default value is acceptable; adjust as necessary
        '''
    )
    
    # Now alter columns to NOT NULL
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('user_name', nullable=False)
        batch_op.alter_column('court_name', nullable=False)
        batch_op.alter_column('reserved_seat', nullable=False)
    
    # Drop the old column if it's truly no longer needed
    # Consider backing up or migrating data if this column contains important historical data
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('reserved_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_on', sa.DATETIME(), nullable=False))  # Consider handling data if needed
        batch_op.drop_column('reserved_seat')
        batch_op.drop_column('court_name')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
