"""Remove profile_picture_url from User model

Revision ID: 136b65e0b86e
Revises: 237e9d477e56
Create Date: 2024-10-10 20:31:21.834959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136b65e0b86e'
down_revision = '237e9d477e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###