"""Change profile_picture to LargeBinary

Revision ID: 237e9d477e56
Revises: 3a550b6fa03f
Create Date: 2024-10-10 02:57:47.653574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237e9d477e56'
down_revision = '3a550b6fa03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=256), nullable=True))
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###
