"""Add time_slots field to Court model

Revision ID: 3abff3e66aba
Revises: cdc93e21158f
Create Date: 2024-08-31 22:23:44.232589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abff3e66aba'
down_revision = 'cdc93e21158f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_slots', sa.Text(), nullable=True))
        batch_op.drop_column('available_date')
        batch_op.drop_column('available_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_time', sa.VARCHAR(length=50), server_default=sa.text("'00:00 - 00:00'"), nullable=False))
        batch_op.add_column(sa.Column('available_date', sa.DATE(), server_default=sa.text("'1970-01-01'"), nullable=False))
        batch_op.drop_column('time_slots')

    # ### end Alembic commands ###
