"""Change profile_picture to Text for base64 storage

Revision ID: 423b7da5c928
Revises: 136b65e0b86e
Create Date: 2024-10-10 21:00:35.594967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423b7da5c928'
down_revision = '136b65e0b86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('temp_profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_profile_picture', sa.BLOB(), nullable=True))
        batch_op.alter_column('profile_picture',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
