"""Add game_id to Reservation

Revision ID: 4e548dc223ba
Revises: 768f53cc15ce
Create Date: 2024-08-21 01:41:28.223008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e548dc223ba'
down_revision = '768f53cc15ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=False))
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('reserved_on',
               existing_type=sa.DATETIME(),
               nullable=True)
        # Specify the constraint name if known, otherwise comment out the drop_constraint
        # batch_op.drop_constraint('fk_court_id', type_='foreignkey')  # Example
        batch_op.create_foreign_key('fk_game_id', 'game', ['game_id'], ['id'])
        batch_op.drop_column('court_id')
        batch_op.drop_column('court_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('court_name', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('court_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_game_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_court_id', 'court', ['court_id'], ['id'])
        batch_op.alter_column('reserved_on',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('user_name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###