"""Adding properties

Revision ID: 508079cdaba9
Revises: a3b41f864e52
Create Date: 2024-07-28 02:35:48.562203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508079cdaba9'
down_revision = 'a3b41f864e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_of_players', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('level_of_players')

    # ### end Alembic commands ###
