"""Add GroupingProduct table.

Revision ID: 74dcd9cbc4fd
Revises: c56f8ea65fc4
Create Date: 2024-06-16 02:23:57.414338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74dcd9cbc4fd'
down_revision = 'c56f8ea65fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grouping_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('discount_rate', sa.Float(), nullable=False),
    sa.Column('total_needed', sa.Integer(), nullable=False),
    sa.Column('current_participants', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grouping_product')
    # ### end Alembic commands ###
