"""Add players_joined field to Game model again

Revision ID: 768f53cc15ce
Revises: c8a96a281d9a
Create Date: 2024-08-19 23:01:36.746290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768f53cc15ce'
down_revision = 'c8a96a281d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('players_joined', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('players_joined')

    # ### end Alembic commands ###
