"""Add players_joined column to Court model

Revision ID: dbabfe5db1ca
Revises: fffed24b6f99
Create Date: 2024-08-03 14:10:17.627921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbabfe5db1ca'
down_revision = 'fffed24b6f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('court')
    op.drop_table('purchase')
    op.drop_table('reservation')
    op.drop_table('product')
    op.drop_table('grouping_product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grouping_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('original_price', sa.FLOAT(), nullable=False),
    sa.Column('discount_rate', sa.FLOAT(), nullable=False),
    sa.Column('total_needed', sa.INTEGER(), nullable=False),
    sa.Column('current_participants', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('court_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('court_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('reserved_seat', sa.INTEGER(), nullable=False),
    sa.Column('reserved_on', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['court.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('purchase_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('available_seats', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('available_date', sa.DATE(), server_default=sa.text("'1970-01-01'"), nullable=False),
    sa.Column('available_time', sa.VARCHAR(length=50), server_default=sa.text("'00:00 - 00:00'"), nullable=False),
    sa.Column('image', sa.VARCHAR(length=200), nullable=True),
    sa.Column('level_of_players', sa.VARCHAR(length=50), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
