"""change propertie to null true

Revision ID: fffed24b6f99
Revises: 508079cdaba9
Create Date: 2024-07-29 02:00:41.461480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffed24b6f99'
down_revision = '508079cdaba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.alter_column('level_of_players',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('level_of_players',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
