name: Deploy Backend with Migrations to PostgreSQL Database

on:
  push:
    branches:
      - main  # Adjust to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      # Run migrations
      - name: Run database migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          . venv/bin/activate
          flask db migrate -m "Auto migration"  # Only generate new migration scripts if there are changes
          flask db upgrade  # Apply the migrations

      # Deploy application
      - name: Deploy to Render
        run: |
          . venv/bin/activate
          gunicorn app:app --workers 3 --bind 0.0.0.0:8000
